### ISSUE TITLE
Calling step with demo data : Error with gzip

### ISSUE THREAD

**Issue by RomainBosselut** [jasminezhoulab/cfSNV_docker#1]
Hello, 
I work with ultra-deep targeted panel sequencing data (37 genes).
I want to know if you think cfSNV can be used to detect low-frequencie variants with my data ?

Furthermore, I tried to use your container with demo data but I had an error message for the calling step.
In fact, I transformed your docker image into a singularity container (because we don't use docker on our cluster).

The message error is : 

```
gzip: /usr/local/lib/R/library/cfSNV/extdata/RF41_overlap.sklearn24.sav.gz: No such file or directory
gzip: /usr/local/lib/R/library/cfSNV/extdata/RF41_nonoverlap.sklearn24.sav.gz: No such file or directory
```

Do you have any idea on what's going wrong and what I can do  ? 
Thanks
Romain

**Comment by RoseHuRan** [comment]
Hi Romain,

Yes, we think that cfSNV can be used to detect low-frequency variants with your data. 

You may try the following ways to solve the problem:
1. Use the cfSNV Docker image on Docker Hub to transform it into a singularity container: https://hub.docker.com/repository/docker/ranhu/cfsnv-docker/general.
2. If it still doesn't work, use the cfSNV R package: https://github.com/jasminezhoulab/cfSNV.

Hope it helps!

Ran

**Comment by RomainBosselut** [comment]
ok thank you Ran

**Comment by Zzy190516** [comment]
Hello, 

I have also met the error:

gzip: /usr/local/lib/R/library/cfSNV/extdata/RF41_overlap.sklearn24.sav.gz: No such file or directory
gzip: /usr/local/lib/R/library/cfSNV/extdata/RF41_nonoverlap.sklearn24.sav.gz: No such file or directory

And I am downloading  cfSNV Docker image on Docker Hub and re-try. So I want to know whether there are any difference between the image on Docker Hub and github?

Thanks
Zhenyu Zhang
